# Netlify configuration file

[build]
  # This command is run to build your site.
  command = "npm run build"
  # This is the directory that contains the built site.
  publish = "dist/client"

# Redirect rule for Single Page Applications (SPAs) like React, Vue, or Angular.
# This ensures that all routes are handled by your index.html file.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
